# tm229.ini - Copyright (c) 1992, I.P. Sharp Associates
#
# @(#)tm229.init	1.1.1.1 92/07/06
#
# Initialization File for SAX System for:
#   TM228/TM229 (aka TM3000; Motorola VT220 compatible)
#   assumes APL font downloaded
#
# Function               Keystroke
# ========               =========
#  overstrike            ctrl-P
-o^P
#  APL escape            ctrl-A
-Z^A
# choose special output translate table 
#
-O$SAXDIR/lib/term/tm220tab
