#!/bin/sh 
# lwreset - Copyright (c) 1993, Soliton Associates Limited
#
# @(#)lwreset	1.3 93/06/08
# $Header: /usr/cvsroot/sax/src/lib/lp/lwreset,v 1.2 2000/11/14 20:19:54 dragan Exp $
# UNIX script to accomodate PostScript printing

Prt=${Prt:-LW}
Tmp='/tmp/reset.lw'
echo 'systemdict begin quit' >$Tmp
echo "\004" >>$Tmp
if test -f /usr/bin/arch -o -f /bin/arch
	then cat $Tmp | lpr -h -P$Prt
else cat $Tmp | lp
fi
rm $Tmp
echo 'Reseting laser printer'
date
